#!/bin/bash
set -e

echo "Initializing Workspace..."

# Clone VibeVoice if it hasn't been cloned yet
if [ ! -d "VibeVoice" ]; then
    echo "Cloning VibeVoice repository..."
    git clone https://github.com/microsoft/VibeVoice.git VibeVoice
fi

# Create persistent and temporary directories locally
mkdir -p final_outputs temp_assets stock_videos VibeVoice/demo/voices VibeVoice/outputs

# FIX: Force open permissions so Gradio can read/serve the MP4s generated by FFmpeg inside the volume
chmod -R 777 final_outputs temp_assets stock_videos VibeVoice/outputs

echo "Workspace setup complete."